DO $$
BEGIN
    ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SECONDARY_ANALYZING';
    ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SECONDARY_REVIEW';
    ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SECONDARY_FAILED';
END $$;
